#pragma once
#include <QApplication>
#include <QButtonGroup>
#include <QComboBox>
#include <QCoreApplication>
#include <QDebug>
#include <QDoubleSpinBox>
#include <QFileDialog>
#include <QGroupBox>
#include <QHBoxLayout>
#include <QImage>
#include <QLabel>
#include <QLineEdit>
#include <QMainWindow>
#include <QMetaMethod>
#include <QMetaObject>
#include <QObject>
#include <QPixmap>
#include <QPushButton>
#include <QRadioButton>
#include <QScrollArea>
#include <QSlider>
#include <QSpinBox>
#include <QStackedLayout>
#include <QStackedWidget>
#include <QString>
#include <QThread>
#include <QVBoxLayout>
#include <QVariant>
#include <QWidget>
#include <algorithm>
#include <cctype>
#include <chrono>
#include <filesystem>
#include <future> // std::async, std::future
#include <iostream>
#include <memory>
#include <mutex> // std::mutex, std::lock_guard
#include <opencv2/dnn_superres.hpp>
#include <opencv2/opencv.hpp>
#include <ostream>
#include <ratio>
#include <string>
#include <vector>